#!/usr/bin/env bash
# ============================================================
# configure-firebase.sh
# firebase-config.js ko automatically fill karta hai Firebase CLI
# ke through. Isko apne computer par (jahan is project ka folder
# hai) chalaayein — Claude ke sandbox mein internet nahi hai isliye
# yahan se directly nahi ho sakta.
#
# USAGE:
#   chmod +x configure-firebase.sh
#   ./configure-firebase.sh
#
# Requirements: Node.js installed
# ============================================================
set -euo pipefail

CONFIG_FILE="firebase-config.js"

echo "== Step 1: Firebase CLI check =="
if ! command -v firebase >/dev/null 2>&1; then
  echo "firebase-tools nahi mila. Install kar raha hoon..."
  npm install -g firebase-tools
fi
echo "firebase-tools OK: $(firebase --version)"

echo
echo "== Step 2: Login =="
firebase login --no-localhost || firebase login

echo
echo "== Step 3: Project select karein =="
echo "Aapke Firebase projects:"
firebase projects:list
read -rp "Project ID paste karein (jise use karna hai): " PROJECT_ID

echo
echo "== Step 4: Web App dhoondhna/banana =="
APPS_JSON="$(firebase apps:list WEB --project "$PROJECT_ID" --json)"
APP_ID="$(node -e "
  const d = JSON.parse(process.argv[1]);
  const apps = d.result || [];
  if (apps.length > 0) { console.log(apps[0].appId); }
" "$APPS_JSON" || true)"

if [ -z "${APP_ID:-}" ]; then
  echo "Koi existing Web App nahi mila — naya bana rahe hain..."
  CREATE_JSON="$(firebase apps:create WEB "Hindi Quiz Portal" --project "$PROJECT_ID" --json)"
  APP_ID="$(node -e "
    const d = JSON.parse(process.argv[1]);
    console.log(d.result.appId);
  " "$CREATE_JSON")"
else
  echo "Existing Web App mil gaya: $APP_ID"
fi

echo
echo "== Step 5: SDK config fetch karke $CONFIG_FILE likh rahe hain =="
SDK_JSON="$(firebase apps:sdkconfig WEB "$APP_ID" --project "$PROJECT_ID" --json)"

node -e "
const fs = require('fs');
const d = JSON.parse(process.argv[1]);
const c = d.result.sdkConfig;
const out = \`// Auto-generated by configure-firebase.sh — \${new Date().toISOString()}
export const firebaseConfig = {
  apiKey: \"\${c.apiKey}\",
  authDomain: \"\${c.authDomain}\",
  projectId: \"\${c.projectId}\",
  storageBucket: \"\${c.storageBucket}\",
  messagingSenderId: \"\${c.messagingSenderId}\",
  appId: \"\${c.appId}\"
};
\`;
fs.writeFileSync(process.argv[2], out);
console.log('Likh diya:', process.argv[2]);
" "$SDK_JSON" "$CONFIG_FILE"

echo
echo "== Step 6: Firestore rules deploy (optional) =="
read -rp "Kya firestore.rules abhi publish karein is project par? (y/n): " DEPLOY_RULES
if [ "$DEPLOY_RULES" = "y" ]; then
  if [ ! -f firebase.json ]; then
    cat > firebase.json <<'EOF'
{
  "firestore": {
    "rules": "firestore.rules"
  }
}
EOF
  fi
  firebase deploy --only firestore:rules --project "$PROJECT_ID"
fi

echo
echo "=========================================="
echo "Ho gaya! $CONFIG_FILE ab aapke Firebase project se configured hai."
echo "Agar Firestore Database Console mein enable nahi kiya hai to"
echo "pehle https://console.firebase.google.com/ -> aapka project -> Firestore Database -> Create database karein."
echo "=========================================="
